/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n8.0-34-g2790dd608c-20251114"
#endif /* AVUTIL_FFVERSION_H */
